name: CI

on:
  push:
    branches:
      - main
      - 'v*'
  pull_request: {}

env:
  CI: 'true'

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    env:
      VOLTA_FEATURE_PNPM: true

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
        with:
          node-version: 22.x
      - name: Install dependencies
        run: pnpm install
      - name: Lint JS
        run: pnpm lint:js
      - name: Test
        run: pnpm test

  try-scenarios:
    name: ${{ matrix.ember-try-scenario }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        ember-try-scenario:
          - ember-lts-3.16
          - ember-lts-3.20
          - ember-release
          - ember-beta
          - ember-canary
          - ember-classic
          - embroider-safe
          - embroider-optimized

    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: 22
      - name: Install dependencies
        run: pnpm install
      - name: Test
        env:
          EMBER_TRY_SCENARIO: ${{ matrix.ember-try-scenario }}
        run: pnpm ember try:one $EMBER_TRY_SCENARIO

        working-directory: packages/test-app
